create table users(
user_id serial PRIMARY KEY,
username VARCHAR
)


create table users2(
user_id INTEGER GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
username VARCHAR
)

create table users3(
user_id INTEGER GENERATED ALWAYS as IDENTITY PRIMARY KEY,
username VARCHAR
)


create table users4(
user_id INTEGER GENERATED ALWAYS as IDENTITY (start WITH 100 INCREMENT by 2),
username VARCHAR
)




insert into users(username) 
values ('Hector')

select * from users




create table usersDual(
id1 int,
id2 int,
PRIMARY key (id1,id2)
)


select gen_random_uuid(),uuid_generate_v4();

drop EXTENSION "uuid-ossp"
create EXTENSION if not EXISTS "uuid-ossp"


create table users5(
"user_id" uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
username VARCHAR
)


INSERT into users5 (username)values(
'Puga'
)

select * from users5


create sequence user_sequence

drop sequence pg_statio_user_sequences
select  currval('user_sequence'),nextval('user_sequence'),currval('user_sequence') 

create TABLE users6 (
user_id INTEGER PRIMARY key DEFAULT nextval('user_sequence'),
username varchar
)